{{- if .Values.FlinkObjectDetectorJob.enabled }}
apiVersion: flink.nautilus.dellemc.com/v1beta1
kind: FlinkCluster
metadata:
  name: flink-object-detector
  labels:
    name: flink-object-detector
spec:
  imageRef:
    name: cuda10.0flink1.9.1
  zookeeperUrl: zookeeper-client:2181
  storage:
    volumeSource:
      persistentVolumeClaim:
        claimName: data-project
  localStorage:
    replicas: 2
    volumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 10G

  jobManager:
    replicas: 1
    memory: 1000M
    heap: 200m
    cpu: 1000m

  taskManager:
    replicas: {{ .Values.FlinkObjectDetectorJob.taskManager.replicas }}
    memory: {{ .Values.FlinkObjectDetectorJob.taskManager.memory }}
    cpu: {{ .Values.FlinkObjectDetectorJob.taskManager.cpu }}
    heap: {{ .Values.FlinkObjectDetectorJob.taskManager.heap }}
    numberOfTaskSlots: {{ .Values.FlinkObjectDetectorJob.taskManager.taskSlots }}
---
apiVersion: flink.nautilus.dellemc.com/v1beta1
kind: FlinkApplication
metadata:
  name: flink-object-detector
  labels:
    app: videoprocessor
    component: FlinkObjectDetectorJob
    release: {{ $.Release.Name }}
spec:
  flinkVersion: 1.9.1
  clusterSelector:
    name: flink-object-detector
  mavenCoordinate: {{ .Values.mavenCoordinate.group }}:{{ .Values.mavenCoordinate.artifact }}:{{ .Values.mavenCoordinate.version }}
  mainClass: io.pravega.example.videoprocessor.FlinkObjectDetectorJob
  parallelism: {{ .Values.FlinkObjectDetectorJob.parallelism }}
  state: started
  parameters:
    - name: enableOperatorChaining
      value: {{ .Values.FlinkObjectDetectorJob.enableOperatorChaining | quote }}
    - name: framesPerSec
      value: {{ .Values.FlinkObjectDetectorJob.framesPerSec | quote }}
    - name: input-stream
      value: {{ .Values.FlinkObjectDetectorJob.input.stream | quote }}
    - name: input-minNumSegments
      value: {{ .Values.FlinkObjectDetectorJob.input.minNumSegments | quote }}
    - name: maxOutOfOrdernessMs
      value: {{ .Values.FlinkObjectDetectorJob.maxOutOfOrdernessMs | quote }}
    - name: output-stream
      value: {{ .Values.FlinkObjectDetectorJob.output.stream | quote }}
    - name: output-minNumSegments
      value: {{ .Values.FlinkObjectDetectorJob.output.minNumSegments | quote }}
    - name: readerParallelism
      value: {{ .Values.FlinkObjectDetectorJob.readerParallelism | quote }}
    - name: scope
      value: {{ $.Release.Namespace | quote }}
    - name: startAtTail
      value: {{ .Values.FlinkObjectDetectorJob.startAtTail | quote }}
    {{- range $key, $value := .Values.FlinkObjectDetectorJob.appParameters }}
    - name: {{ $key | quote }}
      value: {{ $value | quote }}
    {{- end }}
  {{- end }}
