{{- if .Values.FlinkObjectDetectorJob.enabled }}
apiVersion: flink.nautilus.dellemc.com/v1beta1
kind: FlinkCluster
metadata:
  name: flink-object-detector
  labels:
    name: flink-object-detector
spec:
  imageRef:
    name: 1.7.2
  zookeeperUrl: zookeeper-client:2181
  storage:
    volumeSource:
      persistentVolumeClaim:
        claimName: data-project
  localStorage:
    replicas: 2
    volumeClaimTemplate:
      accessModes: [ ReadWriteOnce ]
      storageClassName: standard
      resources:
        requests:
          storage: 5Gi
  jobManager:
    replicas: 1
    memory: 1024M
    cpu: 250m
  taskManager:
    replicas: {{ .Values.FlinkObjectDetectorJob.taskManager.replicas }}
    memory: {{ .Values.FlinkObjectDetectorJob.taskManager.memory }}
    cpu: {{ .Values.FlinkObjectDetectorJob.taskManager.cpu }}
    numberOfTaskSlots: {{ .Values.FlinkObjectDetectorJob.taskManager.taskSlots }}
---
apiVersion: flink.nautilus.dellemc.com/v1beta1
kind: FlinkApplication
metadata:
  name: flink-object-detector
  labels:
    app: videoprocessor
    component: FlinkObjectDetectorJob
    release: {{ $.Release.Name }}
spec:
  flinkVersion: 1.7.2
  imageRef: cuda10.0flink1.7.2v3
  clusterSelector:
    name: flink-object-detector
  mavenCoordinate: {{ .Values.mavenCoordinate.group }}:{{ .Values.mavenCoordinate.artifact }}:{{ .Values.mavenCoordinate.version }}
  mainClass: io.pravega.example.videoprocessor.FlinkObjectDetectorJob
  parallelism: {{ .Values.FlinkObjectDetectorJob.parallelism }}
  state: started
  parameters:
    - name: enableOperatorChaining
      value: {{ .Values.FlinkObjectDetectorJob.enableOperatorChaining | quote }}
    - name: scope
      value: {{ $.Release.Namespace | quote }}
    - name: startAtTail
      value: {{ .Values.FlinkObjectDetectorJob.startAtTail | quote }}
    - name: maxOutOfOrdernessMs
      value: {{ .Values.FlinkObjectDetectorJob.maxOutOfOrdernessMs | quote }}
{{- end }}
