{{- if .Values.MultiVideoGridJob.enabled }}
apiVersion: flink.nautilus.dellemc.com/v1beta1
kind: FlinkCluster
metadata:
  name: multi-video-grid
  labels:
    name: multi-video-grid
spec:
  imageRef:
    name: 1.9.1-2.12
  zookeeperUrl: zookeeper-client:2181
  storage:
    volumeSource:
      persistentVolumeClaim:
        claimName: data-project
  localStorage:
    replicas: 2
    volumeClaimTemplate:
      accessModes: [ ReadWriteOnce ]
      storageClassName: standard
      resources:
        requests:
          storage: 5Gi
  jobManager:
    replicas: 1
    memory: 1024M
    cpu: 250m
  taskManager:
    replicas: {{ .Values.MultiVideoGridJob.taskManager.replicas }}
    memory: {{ .Values.MultiVideoGridJob.taskManager.memory }}
    cpu: {{ .Values.MultiVideoGridJob.taskManager.cpu }}
    numberOfTaskSlots: {{ .Values.MultiVideoGridJob.taskManager.taskSlots }}
---
apiVersion: flink.nautilus.dellemc.com/v1beta1
kind: FlinkApplication
metadata:
  name: multi-video-grid
  labels:
    app: videoprocessor
    component: MultiVideoGridJob
    release: {{ $.Release.Name }}
spec:
  flinkVersion: 1.9.1
  clusterSelector:
    name: multi-video-grid
  mavenCoordinate: {{ .Values.mavenCoordinate.group }}:{{ .Values.mavenCoordinate.artifact }}:{{ .Values.mavenCoordinate.version }}
  mainClass: io.pravega.example.videoprocessor.MultiVideoGridJob
  parallelism: {{ .Values.MultiVideoGridJob.parallelism }}
  state: started
  parameters:
    - name: checkpointIntervalMs
      value: {{ .Values.MultiVideoGridJob.checkpointIntervalMs | quote }}
    - name: chunkSizeBytes
      value: {{ .Values.MultiVideoGridJob.chunkSizeBytes | quote }}
    - name: enableOperatorChaining
      value: {{ .Values.MultiVideoGridJob.enableOperatorChaining | quote }}
    - name: framesPerSec
      value: {{ .Values.MultiVideoGridJob.framesPerSec | quote }}
    - name: imageHeight
      value: {{ .Values.MultiVideoGridJob.imageHeight | quote }}
    - name: imageWidth
      value: {{ .Values.MultiVideoGridJob.imageWidth | quote }}
    - name: input-minNumSegments
      value: {{ .Values.MultiVideoGridJob.input.minNumSegments | quote }}
    - name: input-stream
      value: {{ .Values.MultiVideoGridJob.input.stream | quote }}
    - name: maxOutOfOrdernessMs
      value: {{ .Values.MultiVideoGridJob.maxOutOfOrdernessMs | quote }}
    - name: output-minNumSegments
      value: {{ .Values.MultiVideoGridJob.output.minNumSegments | quote }}
    - name: output-stream
      value: {{ .Values.MultiVideoGridJob.output.stream | quote }}
    - name: readerParallelism
      value: {{ .Values.MultiVideoGridJob.readerParallelism | quote }}
    - name: rebalance
      value: {{ .Values.FlinkObjectDetectorJob.rebalance | quote }}
    - name: scope
      value: {{ $.Release.Namespace | quote }}
    - name: startAtTail
      value: {{ .Values.MultiVideoGridJob.startAtTail | quote }}
  {{- end }}