{{- if .Values.VideoDataGeneratorJob.enabled }}
apiVersion: flink.nautilus.dellemc.com/v1beta1
kind: FlinkCluster
metadata:
  name: video-data-generator
  labels:
    name: video-data-generator
spec:
  imageRef:
    name: 1.9.1-2.12
  zookeeperUrl: zookeeper-client:2181
  storage:
    volumeSource:
      persistentVolumeClaim:
        claimName: data-project
  localStorage:
    replicas: 2
    volumeClaimTemplate:
      accessModes: [ ReadWriteOnce ]
      storageClassName: standard
      resources:
        requests:
          storage: 5Gi
  jobManager:
    replicas: 1
    memory: 1024M
    cpu: 250m
  taskManager:
    replicas: {{ .Values.VideoDataGeneratorJob.taskManager.replicas }}
    memory: {{ .Values.VideoDataGeneratorJob.taskManager.memory }}
    cpu: {{ .Values.VideoDataGeneratorJob.taskManager.cpu }}
    numberOfTaskSlots: {{ .Values.VideoDataGeneratorJob.taskManager.taskSlots }}
---
apiVersion: flink.nautilus.dellemc.com/v1beta1
kind: FlinkApplication
metadata:
  name: video-data-generator
  labels:
    app: videoprocessor
    component: VideoDataGeneratorJob
    release: {{ $.Release.Name }}
spec:
  flinkVersion: 1.9.1
  clusterSelector:
    name: video-data-generator
  mavenCoordinate: {{ .Values.mavenCoordinate.group }}:{{ .Values.mavenCoordinate.artifact }}:{{ .Values.mavenCoordinate.version }}
  mainClass: io.pravega.example.videoprocessor.VideoDataGeneratorJob
  parallelism: {{ .Values.VideoDataGeneratorJob.parallelism }}
  state: started
  parameters:
    - name: enableCheckpoint
      value: "false"
    - name: enableOperatorChaining
      value: {{ .Values.VideoDataGeneratorJob.enableOperatorChaining | quote }}
    - name: scope
      value: {{ $.Release.Namespace | quote }}
    - name: output-stream
      value: {{ .Values.VideoDataGeneratorJob.output.stream | quote }}
    - name: output-minNumSegments
      value: {{ .Values.VideoDataGeneratorJob.output.minNumSegments | quote }}
    - name: numCameras
      value: {{ .Values.VideoDataGeneratorJob.numCameras | quote }}
    - name: imageWidth
      value: {{ .Values.VideoDataGeneratorJob.imageWidth | quote }}
    - name: framesPerSec
      value: {{ .Values.VideoDataGeneratorJob.framesPerSec | quote }}
    - name: chunkSizeBytes
      value: {{ .Values.VideoDataGeneratorJob.chunkSizeBytes | quote }}
    - name: useCachedFrame
      value: {{ .Values.VideoDataGeneratorJob.useCachedFrame | quote }}
#    - name: writeToPravega
#      value: "false"
{{- end }}
