{{- if .Values.VideoReaderJob.enabled }}
apiVersion: flink.nautilus.dellemc.com/v1beta1
kind: "FlinkApplication"
metadata:
  name: "video-reader-job"
  labels:
    app: videoprocessor
    component: VideoReaderJob
    release: {{ $.Release.Name }}
spec:
  flinkVersion: 1.7.2
  mavenCoordinate: {{ .Values.mavenCoordinate.group }}:{{ .Values.mavenCoordinate.artifact }}:{{ .Values.mavenCoordinate.version }}

  parallelism: {{ .Values.VideoReaderJob.parallelism }}

  state: started

  parameters:
    - name: jobClass
      value: "io.pravega.example.videoprocessor.VideoReaderJob"
    - name: scope
      value: {{ $.Release.Namespace | quote }}
    - name: input-stream
      value: {{ .Values.MultiVideoGridJob.output.stream | quote }}
    - name: input-minNumSegments
      value: {{ .Values.MultiVideoGridJob.output.minNumSegments | quote }}
    - name: enableOperatorChaining
      value: "false"
{{- end }}
