mavenCoordinate:
  group: io.pravega.example.video
  artifact: flinkprocessor
  version: 0.1.0

FlinkObjectDetectorJob:
  enabled: true
  parallelism: 1
  enableOperatorChaining: "false"
  input:
    stream: object-detector-input-video
    minNumSegments: 1
  output:
    stream: object-detector-output-video
    minNumSegments: 1
  startAtTail: "true"
  maxOutOfOrdernessMs: 1000
  taskManager:
    cpu: 2000m
    heap: 2000m
    memory: 8G
    replicas: 1
    taskSlots: 1

VideoDataGeneratorJob:
  enabled: false
  parallelism: 1
  enableOperatorChaining: "false"
  output:
    stream: generated-video
    minNumSegments: 1
  useCachedFrame: "false"
  numCameras: 1
  imageWidth: 416
  framesPerSec: 1.0
  chunkSizeBytes: 6292480
  taskManager:
    replicas: 1
    heap: 500m
    memory: 1G
    cpu: 250m
    taskSlots: 1

MultiVideoGridJob:
  enabled: false
  parallelism: 1
  readerParallelism: -1
  enableOperatorChaining: "false"
  input:
    stream: generated-video
    minNumSegments: 1
  output:
    stream: grid-video
    minNumSegments: 1
  imageWidth: 75
  framesPerSec: 1.0
  chunkSizeBytes: 6292480
  startAtTail: "false"
  maxOutOfOrdernessMs: 1000
  checkpointIntervalMs: 300000
  taskManager:
    replicas: 1
    memory: 8G
    cpu: 1000m
    taskSlots: 4

VideoReaderJob:
  enabled: false
  parallelism: 1
  enableOperatorChaining: "false"
  startAtTail: "false"
  maxOutOfOrdernessMs: 1000
  taskManager:
    replicas: 1
    memory: 1G
    cpu: 250m
    taskSlots: 1


